import type { Agent, AgentTask, TaskQueue } from './types';

export const getMockAgents = (): Agent[] => [
  {
    id: 'jos',
    name: 'Jos',
    role: 'Mission Control',
    status: 'active',
    health: 98,
    currentTask: 'Coordinating team workflow',
    tasksCompleted: 1247,
    uptime: '47d 12h 35m',
    lastSeen: new Date(),
  },
  {
    id: 'boeboesh',
    name: 'Boeboesh',
    role: 'Coding & Build',
    status: 'active',
    health: 95,
    currentTask: 'Building Mission Control Dashboard',
    tasksCompleted: 892,
    uptime: '45d 8h 22m',
    lastSeen: new Date(),
  },
  {
    id: 'guido',
    name: 'Guido',
    role: 'Creative & Design',
    status: 'idle',
    health: 100,
    tasksCompleted: 634,
    uptime: '42d 3h 15m',
    lastSeen: new Date(Date.now() - 300000),
  },
  {
    id: 'rover',
    name: 'Rover',
    role: 'Research & Analysis',
    status: 'active',
    health: 92,
    currentTask: 'Market research for Q2',
    tasksCompleted: 1089,
    uptime: '48d 1h 47m',
    lastSeen: new Date(),
  },
  {
    id: 'bavo',
    name: 'Bavo',
    role: 'Nieuws & Content',
    status: 'idle',
    health: 100,
    tasksCompleted: 0,
    uptime: '0d 0h 0m',
    lastSeen: new Date(Date.now() - 600000),
  },
  {
    id: 'bram',
    name: 'Bram',
    role: 'Product Owner',
    status: 'active',
    health: 100,
    currentTask: 'Reviewing dashboard progress',
    tasksCompleted: 456,
    uptime: '50d 6h 12m',
    lastSeen: new Date(),
  },
];

export const getMockTasks = (): AgentTask[] => [
  {
    id: 'task-1',
    title: 'Build Trading Dashboard',
    description: 'Complete P1 features with real-time updates',
    status: 'in_progress',
    progress: 85,
    eta: '15 min',
    startedAt: new Date(Date.now() - 3600000),
    sessionKey: 'agent:boeboesh:subagent:task-1',
    agentName: 'Boeboesh',
  },
  {
    id: 'task-2',
    title: 'Build Agents Monitor',
    description: 'P2 features with status tracking and health monitoring',
    status: 'in_progress',
    progress: 45,
    eta: '1 hr',
    startedAt: new Date(Date.now() - 1800000),
    sessionKey: 'agent:boeboesh:subagent:task-2',
    agentName: 'Boeboesh',
  },
  {
    id: 'task-3',
    title: 'Deploy to Vercel',
    description: 'Production deployment with environment setup',
    status: 'pending',
    progress: 0,
    agentName: 'Jos',
  },
  {
    id: 'task-4',
    title: 'Integrate Bybit API',
    description: 'Replace mock data with real-time Bybit WebSocket',
    status: 'pending',
    progress: 0,
    agentName: 'Boeboesh',
  },
  {
    id: 'task-5',
    title: 'UI Polish & Testing',
    description: 'Final polish, accessibility, and Playwright tests',
    status: 'pending',
    progress: 0,
    agentName: 'Guido',
  },
];

export const getMockTaskQueue = (): TaskQueue => ({
  pending: 3,
  inProgress: 2,
  completed: 127,
  failed: 2,
  cancelled: 0,
});
